### ISSUE TITLE
Convert to chef-ingredient

### ISSUE THREAD

**Issue by elliott-davis** [chef-cookbooks/supermarket-omnibus-cookbook#11]
In leu of chef-server-ingredient being deprecated we should convert to chef-ingredient

**Comment by irvingpop** [comment]
+1 -  I believe @binamov is working on this in a branch

**Comment by bigbam505** [comment]
Yeah this is currently broken just an FYI a quick fix if you can't get the `chef-ingredient` cookbook updated is to lock down `chef-server-ingredient` to `0.4.0`.

**Comment by pmoosh** [comment]
@bigbam505 thx.
Right now chef fails with:
ERROR: undefined method `repository' for Chef::Resource::ChefServerIngredient

**Comment by MSadir** [comment]
Hi all, any news on this? I don't see any branches on @binamov 's forked repository.

**Comment by RavenB** [comment]
Can we update the cookbook especially now that the other is deprecated and this is the favored cookbook ?

**Comment by wfindley** [comment]
I was playing around with this a few days ago on centos.  The latest (as of this writing) version of chef-ingredient includes `yum-chef::default` (https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/helpers.rb#L69), which sets up a repository (https://github.com/chef-cookbooks/yum-chef/blob/master/recipes/default.rb#L21).  I got it to correctly call an yum installation action on a package named supermarket if I did this: `chef_ingredient 'supermarket'`.  

However, the package doesn't install, because it was unsigned. `Yum-chef::default` sets `gpgcheck true` (https://github.com/chef-cookbooks/yum-chef/blob/master/recipes/default.rb#L30).  It seem like the newest alpha 2.0.0 package is signed as of this commit? https://github.com/chef/omnibus-supermarket/commit/bdb1622c961e6e9efae7e9fda67486f6ce1f9a16  I'll play around with this today.  If I get it working, I'll open a PR.

**Comment by TinaTina** [comment]
:+1:

**Comment by nellshamrell** [comment]
Yes indeed, the newest alpha 2.0.0 package is now signed.

**Comment by MSadir** [comment]
So I have a working version - https://github.com/MSadir/supermarket-omnibus-cookbook. Although I haven't changed any tests or anything. I will have a look at them later today but anyone should feel free to change the tests and submit a PR if you want.

**Comment by pmoosh** [comment]
Any ideas when there is progress on these issues - I think they are all related.

**Comment by irvingpop** [comment]
Fixed by https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/pull/17
