### ISSUE TITLE
Remove dependency on fancy_execute

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/supermarket-omnibus-cookbook#27]
Alternatively, if  roll in `fancy_execute` code into the Chef core.

Reason:
Monkeypatching core chef resource. Expands the surface area of things that can go BOOM.

**Comment by cwebberOps** [comment]
@vinyar right, but we don't currently have the bandwidth to add it to core Chef and the cookbook is heavily used in internal Delivery pipelines. IMHO, a break will be caught well before it blows up here. Removing something that provides a huge amount of value because it "could" go BOOM seems like the wrong thing to do.

**Comment by vinyar** [comment]
alrighty. As long as it's covered and tested I'm cool

**Comment by vinyar** [comment]
closing but reserving the right to reopen :yum:
